---

- name: Deploy Docker containers into application server
  hosts: app
  gather_facts: yes
  vars: 
    aws_region: ap-south-1
    ecr_registry_url: 829173323501.dkr.ecr.ap-south-1.amazonaws.com
  tasks:
    - name: Ensure the target system is Ubuntu-based
      assert:
        that:
          - ansible_facts['os_family'] == 'Debian'  # Ubuntu is based on Debian
        fail_msg: "This playbook is intended for Ubuntu/Debian-based systems only."
    - name: Check Docker version
      shell: docker --version
      register: docker_version
    - name: Login into ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry_url }}