---

- name: Deploy Docker containers into application server
  hosts: app
  remote_user: ubuntu
  vars_files:
    - deploy_vars.yml
  tasks:
    - name: Login into ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ goo_ecr_registry_url }}
      register: ecr_login

    - name: Pull Docker Images for API
      shell: |
        docker pull {{ goo_ecr_registry_url }}/{{ docker_image_api }}
      
    - name: Pull Docker Images for cron
      shell: |
        docker pull {{goo_ecr_registry_url}}/{{ docker_image_cron }}

    - name: Container API Run from docker Images
      shell: |
        docker run -d \
          --name {{ container_name_api }} -p 3000:3000 \
          {{ goo_ecr_registry_url }}/{{ docker_image_api }}
      
    - name: Container Cron Run from docker Images
      shell: |
        docker run -d \
          --name {{ container_name_cron }} -p 4000:4000 \
          {{ goo_ecr_registry_url }}/{{ docker_image_cron }}
      

