# Stage 1: Build
FROM node:16-alpine AS build    #single microservices for single module docker files this is multistage docker-file

# Set the working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM gcr.io/distroless/nodejs:16

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/package.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules

EXPOSE 5002

ENV NODE_ENV=staging

CMD ["dist/src/main.js"]
