#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2
- name: Vpc details
  amazon.aws.ec2_vpc_net:
    name: my-default-vpc
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    cidr_block: "{{ cidr_block }}"
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "AnsibleServer"
    key_name: "{{ key_name }}"
    instance_type: "{{ type }}"
    security_group: "{{ sg }}"
    aws_region: "{{ region }}"
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{ image_ami }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          delete_on_termination: true
  register: instance_info
#Installing Oracle jdk in server
- name: Installing Oracle jdk in server 
  ansible.builtin.import_tasks: download.yml
    
- name: Download Gradle Binary 
  ansible.builtin.import_tasks: download.yml

    



    
