#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2
- name: creating instance in ubuntu
  amazon.aws.ec2_instance:
    name: "DemoAnsible"
    key_name: "{{ key_name }}"
    instance_type: "{{ type }}"
    region: "{{ region }}"
    security_group: "{{ security_groups_name }}"
    network_interfaces:
      - assign_public_ip: true
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    image_id: "{{ images_id }}"

- name: Waiting For remote connection reachable
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300

- name: Install mysql connection
  ansible.builtin.apt:
    name: mysql-server
    state: present

